# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "2.2.2"

  on_macos do
    on_intel do
      sha256 "7c8dea049a46d1edc37c6bc677287378ee9e2ff91ebc3557041db5d39fdfb2fe"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "edb2bd668b0a897caf8fd0f4f41ea16a5228479f0d7277b581810680bc830329"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ef14be313faa1be2f327a2fab836bdbe686d404729d4415dc3e6ce07141e03c"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb3438699d10cb1b53b7e46eb467bf5b8d5c20e1d6b0523f7485a085092f014a"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Persistent memory for AI agent teams"
  homepage "https://github.com/ashmdev/mnemo-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemo"

  # No zap stanza required

  caveats <<~EOS
    macOS: If you see a Gatekeeper warning, run:

      xattr -d com.apple.quarantine $(brew --prefix)/bin/mnemo

    To get started:

      mnemo setup claude-code    # or: cursor, windsurf, gemini-cli, codex, opencode
      mnemo setup --detect       # auto-detect installed agents
      mnemo status               # verify everything works

    Install starter skills:

      mnemo pack install packs/core
  EOS
end
