# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
      sha256 "330def93f4be7bcf859fe62d9d0ca61043bf11cdf8c032ce46649697be23a58c"
    end
    on_arm do
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
      sha256 "23f5d7a3a07489b51fb66e90b20b573d86eaf870f0ccab39dc958bb3b99957e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
      sha256 "b41aa7a60ebe420ad5eb35469faf3fc760efbadaf4ab147cb2d8ce8e81fc57c2"
    end
    on_arm do
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
      sha256 "ab5721ded9bd42bc95ebfa417723813d6b9c8a64d63642d97aae910693632f74"
    end
  end

  name "mnemo"
  desc "Persistent memory for AI agent teams"
  homepage "https://github.com/ashmdev/mnemo-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemo"

  # No zap stanza required

  caveats <<~EOS
    To get started with mnemo:

      mnemo setup claude-code    # or: cursor, windsurf, gemini-cli, codex, opencode
      mnemo setup --detect       # auto-detect installed agents
      mnemo status               # verify everything works

    Install starter skills for best results:

      mnemo pack install packs/core
  EOS
end
