# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemo" do
  version "2.2.1"

  on_macos do
    on_intel do
      sha256 "0e5db722ee1c867768f98547a6487dbacc08a1c39bf5b093f299791ce91f2b47"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b09930254b525a1c82c73495a670c72f472790e73335fd775b89ad1a02167760"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a18306f6da96b026b9495db3557e0414ba59036a4d5dbd8dcb9d53a2eb2950ab"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f03e80a7de37b9f9c1f5a57b0a921d6f2748d409452597dcde5d9c9194c096e8"
      url "https://github.com/ashmdev/mnemo-releases/releases/download/v#{version}/mnemo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemo"
  desc "Persistent memory for AI agent teams"
  homepage "https://github.com/ashmdev/mnemo-releases"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemo"

  # No zap stanza required

  caveats <<~EOS
    macOS: If you see a Gatekeeper warning, run:

      xattr -d com.apple.quarantine $(brew --prefix)/bin/mnemo

    To get started:

      mnemo setup claude-code    # or: cursor, windsurf, gemini-cli, codex, opencode
      mnemo setup --detect       # auto-detect installed agents
      mnemo status               # verify everything works

    Install starter skills:

      mnemo pack install packs/core
  EOS
end
